### PR TITLE
Migrate plugins to Girder 3 api.

### PR DESCRIPTION
**Pull request by aronhelser**
api and other migration changes, required by Girder 3.

### CODE REVIEW

**Comment by aronhelser** [comment]
getting this failure I'm not sure how to address: @cjh1 do you have any suggestions?

> StateTransitionBehavior
    ✓ does nothing if there's no taskflow
08 07 2019 16:37:45.773:WARN [web-server]: 404: /api/v1/simulations/574c8aa00640fd3f1a3b379f
    fs actions depending on taskflow state
      ✗ does not update folders if not all complete
	Error: spy was not supposed to be called
	    at assert (test/contexts/tests.all.js:8130:9)
	    at Expectation.toNotHaveBeenCalled (test/contexts/tests.all.js:7737:28)
	    at UserContext.<anonymous> (test/contexts/tests.all.js:125576:52)
	    at <Jasmine>

**Comment by cjh1** [comment]
@aronhelser I am not familiar with these tests @jourdain may be able to help, but it looks like "does not update folders if not all complete" is no longer true, may be a change in a redux actions. These tests are client side only, so shouldn't be effected by the server changes.

**Comment by aronhelser** [comment]
OK, I think I'm going to disable the test and proceed....

**Comment by cjh1** [comment]
Good plan.

**Comment by aronhelser** [comment]
Disabling the test worked here. @cjh1 a second for review....

**Comment by aronhelser** [comment]
@cjh1 OK to merge?

**Comment by cjh1** [comment]
@aronhelser Yes, sorry for the delay.

**Comment by aronhelser** [comment]
I think you have to hit the button @cjh1 I don't have write permission.

**Comment by cjh1** [comment]
@aronhelser I can fix that

**Comment by cjh1** [comment]
@aronhelser Try now

**Comment by aronhelser** [comment]
Thanks! Might be good to add Scott W. to HPCCloud as well...

**Comment by cjh1** [comment]
Done

**Pull request merged**
