### PR TITLE
Add guard for launch property

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright This should resolve #488

**Comment by TristanWright** [comment]
LGTM, I got a visualization job running. Any idea why Travis is failing recently too, happens on Cumulus too?

**Comment by cjh1** [comment]
Looks like the Travis issue is Girder related, I will look into it ...

**Comment by TristanWright** [comment]
should I merge this into release?

**Pull request merged**
