### PR TITLE
Placeholder pages

### PR DESCRIPTION
**Pull request by TristanWright**
@cjh1  PTAL

### CODE REVIEW

**Comment by cjh1** [comment]
Not sure if this is by design, but if you delete the last simulation in a project the placeholder doesn't appear until you refresh or navigate away?

**Comment by TristanWright** [comment]
hmmm I cannot reproduce that. Is the simulation being deleted with
multi-select or from the edit page?

On Thu, Apr 7, 2016 at 1:02 PM, Chris Harris <notifications@github.com>
wrote:

> Not sure if this is by design, but if you delete the last simulation in a
> project the placeholder doesn't appear until you refresh or navigate away?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/pull/329#issuecomment-207051084>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
Was from the edit page, I can't recreate anymore either. LGTM

**Comment by TristanWright** [comment]
[merged](https://media.giphy.com/media/vv41HlvfogHAY/giphy.gif)

**Pull request merged**
