### PR TITLE
Fixed Volume misspelling

### PR DESCRIPTION
**Pull request by chetnieter**

### CODE REVIEW

**Comment by cjh1** [comment]
I think volumneSize is used in a couple of other places, they probably need updated too.

**Comment by cjh1** [comment]
@TristanWright PTAL

**Comment by chetnieter** [comment]
I think I got them all. I had to fix a couple in HPCCloud.js. This file is regenerated when you run 'npm run build' right? Should it be stored in the repo?

**Comment by TristanWright** [comment]
Looks like you got all the `volumneSize`'s fixed.
HPCCloud is regenerated when you run `npm run build` you should never have to edit it. I don't know why it's in the repository, we also haven't rebuilt and committed it in a while so I did in the last commit.

LGTM

**Pull request merged**
