### PR TITLE
Ensure output is updated when simulation panel is open

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright I tested logging after this merge and looks like its broken, I don't think my changes broke it as it also broken on master.

**Comment by TristanWright** [comment]
Getting a `No $ref for task`?

**Comment by cjh1** [comment]
I see 
```
TypeError: Cannot read property '$ref' of undefined
    at chpc-min.js:1755
    at l (bower-vendors.js:8)
    at bower-vendors.js:8
    at d.t.$get.d.$eval (bower-vendors.js:9)
    at d.t.$get.d.$digest (bower-vendors.js:8)
    at d.t.$get.d.$apply (bower-vendors.js:9)
    at o (bower-vendors.js:8)
    at v (bower-vendors.js:8)
    at XMLHttpRequest.x.onload (bower-vendors.js:8)
```

**Comment by TristanWright** [comment]
found it, bad syntax

**Pull request merged**
