### PR TITLE
added parameters for updating view in simulation step object

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright This adds a view property to the simulation, it looks like we already have a view property on each simulation step, do we need both?

**Comment by jourdain** [comment]
I don't see why we would need a view property on the simulation itself.

**Comment by cjh1** [comment]
@TristanWright  By the way great to see you pushing code on the server side :-)

**Comment by TristanWright** [comment]
I thought this was applying it to the step? The reason for this was that the `PATCH /simulations/{id}/steps/{stepName}` endpoint was not updating the view attribute? (screenshots from dev-v2)

screen shot 2016-02-23 at 10 27 41

screen shot 2016-02-23 at 10 28 03

**Comment by cjh1** [comment]
@TristanWright I see the confusion now. It was already on the simulation, but you added it to the step. I have pushed a fix that removes it from the simulation and adds a test case.

**Comment by cjh1** [comment]
@TristanWright LGTM. merge if you are happy with additional commits.

**Pull request merged**
