### PR TITLE
New Simput

### PR DESCRIPTION
**Pull request by TristanWright**
addresses #436

### CODE REVIEW

**Comment by TristanWright** [comment]
@cjh1 this is ready to test. PTAL

Merge target is master, let me know if it should be something else

**Comment by TristanWright** [comment]
(requires an `npm instal`l)

**Comment by cjh1** [comment]
@TristanWright This is looking good, a couple of things:

-  [   ] I seems that it doesn't report any errors if the ini is invalid. I seems just to create the project and then you can create simulations without a problem.
-  [   ] I think we should be able to override the ini file at the simulation level. So when you create a simulation, it should default to inheriting the projects ini file, but you should be able to upload ini file to over it. Thoughts?
-  [   ] Related issue #543

**Comment by TristanWright** [comment]
@cjh1

You can override the project ini in the new simulation page now but I should figure out a way to make it apparent to the user.

For #543 I addressed it in the most recent commit: 

screen shot 2016-10-07 at 15 04 30

**Comment by TristanWright** [comment]
In latest commits: 

- the ini validation only looks at sections and if there's an unrecognized one it won't allow you to upload it. 
- new simulation page clarifies what the ini file will do
- edit simulation page shows files

**Comment by cjh1** [comment]
@TristanWright Validation of the ini file seems to work well, it prevents me from uploading a binary file :smile: 

I ran into on issue with the override functionality. Here is the sequence of steps:

1. Create a project with our sample pyfr in file
2. Create a simulation and upload another ini file ( I will send it to you )
3. The value are not overridden ...

We can speak on hangout about this ...

**Comment by TristanWright** [comment]
@cjh1 latest commit should resolve what you were seeing

**Comment by TristanWright** [comment]
addresses #504, #543

**Comment by TristanWright** [comment]
@cjh1 have you had another chance to look at this?

**Comment by cjh1** [comment]
@TristanWright I take a look today.

**Comment by TristanWright** [comment]
latest commit needs an `npm install`. Also old pyfr models will be missing the `Pr` value as the model for that value was updated. (`pr` -> `Pr`)

**Comment by TristanWright** [comment]
@chetnieter @cjh1 huge thing with merging this branch that slipped my mind for which I have been getting some pesky (but not totally deadly) errors this afternoon: 

pyfr-exec projects won't work anymore because there's no pyfr-exec type.

**Pull request merged**
