### PR TITLE
Ec2 cluster

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright I have rebased this branch add added a few things. I am running into an issue at the moment that the client doesn't recognized some server side events:

unrecognized ServerEvent with type "cluster", id "572768d00640fd0962a319c7", and status "launched"
HPCCloud.js:54056 unrecognized ServerEvent with type "cluster", id "572768d00640fd0962a319c7", and status "provisioning"
HPCCloud.js:54056 unrecognized ServerEvent with type "cluster", id "572768d00640fd0962a319c7", and status "error"

We will want to update the client so it accepts changes to the cluster status displays it.

**Comment by TristanWright** [comment]
Ah yes we're not listening to it anywhere: 
https://github.com/Kitware/HPCCloud/blob/3fa1eba69881871c7ff076058848faa6199b0e4f/src/redux/actions/taskflows.js#L346

I'll add the 'cluster' case.

**Comment by cjh1** [comment]
Excellent, you can push it to this branch.

**Comment by TristanWright** [comment]
Moving all event handling out proved tricky, keeping them in actions/taskflows for now. Added better cluster.status events support in latest.

**Comment by cjh1** [comment]
@TristanWright Are you OK if I go head and merge this branch?

**Comment by TristanWright** [comment]
yes go ahead, I'm getting the terminate-instance button in place.

**Pull request merged**
