### PR TITLE
meshtagger fixes

### PR DESCRIPTION
**Pull request by TristanWright**
Will update as commits are added, currently fixes: 

- #116: unknown directive provider
- #111: Return to ongoing meshtagger
- #109: Progress indicator is needed in mesh tagger derivative 
- #89: If the mesh tagger fails we need to report this to the user
- #68: Change spinning gear to something meaningful and informative.

### CODE REVIEW

**Comment by TristanWright** [comment]
@cjh1, I'm seeing the `uncaught session not open` error now in the meshtagger. The tagger is completing early? 

Chrome console: 
```
WebSocket connection to 'ws://localhost:8888/proxy?sessionId=562aa84c0640fd047bb61b62%2F562e9a2f0640fd353bf28212' failed: Error during WebSocket handshake: Unexpected response code: 503
PvwAngularComponents.js:257 Autobahn error null
chpc-min.js:286 broadcasting SSE: job.status uploading
chpc-min.js:286 broadcasting SSE: job.status complete
chpc-min.js:286 broadcasting SSE: task.status error
autobahn.min.js:114 WebSocket connection to 'ws://localhost:8888/proxy?sessionId=562aa84c0640fd047bb61b62%2F562e9a2f0640fd353bf28212' failed: Error during WebSocket handshake: Unexpected response code: 503
PvwAngularComponents.js:257 Autobahn error null
autobahn.min.js:101 Uncaught session not open
```

**Comment by cjh1** [comment]
Do you check if the mesh tagger is still running when you get this error?

**Comment by TristanWright** [comment]
The meshtagger is not running when the errors happen.

**Comment by cjh1** [comment]
The timeout for the mesh tagger is 5 minutes, is this happening before then? If so then there is probably an error occurring when the mesh tagger is run.

**Comment by TristanWright** [comment]
I haven't been able to get the error again, it is a really intermittent error as mentioned before.

**Comment by TristanWright** [comment]
I think #89 (If the mesh tagger fails we need to report this to the user) should be mostly fixed now.

**Comment by cjh1** [comment]
@TristanWright So is this branch ready for me to test?

**Comment by TristanWright** [comment]
I'm a little hesitant to fully say yes, I think be cause the error handling for a tagger or viz task is a little shaky. I can demo it to you and see if there's some things I missed if that would be more efficient.

**Comment by TristanWright** [comment]
@cjh1 This is ready to review, I can't find anything glaring.

**Comment by cjh1** [comment]
@TristanWright I am seeing this when I first start the mesh tagger.

Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.7/$rootScope/inprog?p0=%24digest
    at bower-vendors.js:6
    at f (bower-vendors.js:7)
    at d.$apply (bower-vendors.js:8)
    at setupColoring (PvwAngularComponents.js:174)
    at PvwAngularComponents.js:243
    at chpc-min.js:267
    at l (bower-vendors.js:7)
    at bower-vendors.js:7
    at d.$eval (bower-vendors.js:8)
    at d.$digest (bower-vendors.js:7)

**Comment by cjh1** [comment]
@TristanWright Also after the task completes ( the mesh tagger times out ) I am unable to start the tagger again. I see the following in the console:

error

**Comment by cjh1** [comment]
I am still seeing:

```

GET http://localhost:8888/api/v1/item/56336e6f0640fd6c5e832a25 400 (Bad Request)t @ bower-vendors.js:7$ @ bower-vendors.js:7t.$get.u @ bower-vendors.js:7l @ bower-vendors.js:7(anonymous function) @ bower-vendors.js:7t.$get.d.$eval @ bower-vendors.js:8t.$get.d.$digest @ bower-vendors.js:7t.$get.d.$apply @ bower-vendors.js:8setupColoring @ PvwAngularComponents.js:174(anonymous function) @ PvwAngularComponents.js:254connectionInfo.connection.onopen @ vtkweb-all.min.js:30e.6.q.open.b._session.onjoin @ autobahn.min.js:29e.16.f._socket.onmessage @ autobahn.min.js:95e.18.a.create.window.b.onmessage @ autobahn.min.js:114
chpc-min.js:1285 Invalid item id (56336e6f0640fd6c5e832a25).

```

**Comment by TristanWright** [comment]
> I am still seeing: ... [error]

Looks like it's related to the pvw component? The error `chpc-min-js:1285` goes to [this line](https://github.com/Kitware/HPCCloud/blob/master/src/modules/pv/pv-exo-mesh-viewer-controller.js#L31).

**Comment by TristanWright** [comment]
Looks like the meshItem cleared up the incorrect item error and the I'm not getting the `uncaught session id` anymore. I think this can be merged the master?

**Comment by TristanWright** [comment]
Wait, closeOnDestroy for meshtagger?

**Comment by cjh1** [comment]
@TristanWright closeOnDestroy is off by default, which is what we want I think.

**Pull request merged**
