### PR TITLE
Only show 'Terminate' button for 'provisioned' clusters

### PR DESCRIPTION
**Pull request by cjh1**
We can't currently terminate 'launching' or 'provisioning'

### CODE REVIEW

**Comment by cjh1** [comment]
Fixes #438

**Comment by cjh1** [comment]
@TristanWright This makes some updates to the testing code I would like you to take a look at.

**Comment by TristanWright** [comment]
LGTM, I'm still seeing the "Terminate Instance" button after the cluster has been terminated. 

screen shot 2016-07-26 at 14 05 23

New tests look good too.

**Comment by cjh1** [comment]
We shouldn't see the Terminate EC2 Instance button, can you take a look at it?

**Comment by TristanWright** [comment]
yes i'll take a close look. We add the "terminate instance" button outside of StateTransition which adds the other buttons, so I'll see what's going on.

**Comment by TristanWright** [comment]
This was an interesting dive, the main change is that I added a taskflow action which will trigger the function in StateTransitionBehavior. This action gets called when something about and ec2 cluster is changed so the "terminate instance" button will properly appear and disappear.

@cjh1 PTAL

**Comment by cjh1** [comment]
LGTM, thanks for digging into that.

**Pull request merged**
