### PR TITLE
server status misc

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
WIP

**Comment by TristanWright** [comment]
@cjh1 take a look at the new status page, panels for ec2 show log and terminate button if error or running state.

**Comment by cjh1** [comment]
Looks good. Looks like the active simulation is hard coded? Not sure we want to expose the girder id ( or was this just for debug? ). I think we should change "Terminate Instance" to "Terminate cluster", also not sure about the location?

**Comment by cjh1** [comment]
We probably also want a 'delete' button on the status page for cluster that are in the 'terminated' state.

**Comment by TristanWright** [comment]
Simulation name is hardcoded for now, to find the running simulation on a cluster I need to iterate through the running simulations to find a match.

girder Id is for debug for now yes. I've added a delete button on my local copy. 

Need to tweak the layout some more, I'll ping you when these changes have been made.

**Comment by TristanWright** [comment]
Layout is better. Not a clear way to get a simulation on the cluster.
```
For each simulation:
-> for each step in the simulation:
--> if it has a taskflow, fetch it
---> if the taskflow has a cluster, check the cluster id 
----> if the id's match then return the simulation name
--> else continue
```

**Comment by cjh1** [comment]
How about storing the cluster_id in the simulation metadata?

**Comment by TristanWright** [comment]
Not the case for a fresh ec2 cluster, it's added to taskflow afterwards. 

Is there a way to get ec2 clusterId right after simulation start, or do we need to get it from the taskflow?

**Comment by cjh1** [comment]
Yes, I was thinking that when it added to the taskflow the client could update the simulation metadata. In the ec2 case the cluster is created by the taskflow ...

**Comment by TristanWright** [comment]
Massive diff here. Simulation data gets added to a cluster config when there's a taskflow update [here](https://github.com/Kitware/HPCCloud/pull/400/commits/8d2b8005ef04ca3ade91391dd184f88d15ba9ff8#diff-62936fe6adbe9b57d436c2700c0b48d7R88) which should be run whenever we load a simulation view page.

There could be some misnamed functions from the network rework but I believe I got the bit ones.
PTAL 🎉

**Comment by TristanWright** [comment]
@cjh1  ptal

**Comment by cjh1** [comment]
When I try to create a new cluster, the status of the cluster is not updated without a page refresh ( i.e. I don't see the new public key )

**Comment by cjh1** [comment]
The same goes for clicking the "Test" button, the cluster never refreshes its state without a refresh.

**Comment by cjh1** [comment]
LGTM

**Pull request merged**
