### PR TITLE
Release into master

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
@cjh1 what's the strategy for merging branches like this?

Conflict is with server/taskflows/hpccloud/taskflow/paraview.py

**Comment by cjh1** [comment]
So for cumulus I have been doing there merge locally ( carefully ) and pushing directly to master ( you have to allow maintainers to push to master while you are doing this)

**Comment by TristanWright** [comment]
first conflict is in `server/taskflows/hpccloud/taskflow/paraview.py` should I basically opt for the changes in release?

**Comment by cjh1** [comment]
@chetnieter May be able to help you with the resolution (I think its his changes in master causing the problem), if not I will take a look.

**Pull request merged**
