### PR TITLE
Add cluster filters

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
Fixes #236 #444

**Comment by TristanWright** [comment]
Nothing breaking, but I'm confused what I should be specifically testing, running pyfr on an ec2 instance?

**Comment by cjh1** [comment]
The simple

**Comment by cjh1** [comment]
The simplest way to test this is to a create a 'trad' cluster without any pyfr config i.e. Don't set up openmp or cuda, when you try to run a simulation this cluster should be filtered out of the list.

**Comment by TristanWright** [comment]
ah I thought it was related to ec2 stuff. Yes I see that a trad cluster without a backend is filtered. 

LGTM

**Comment by cjh1** [comment]
The filtered also works for EC2 as well. For example if your create a cluster as part PyFR workflow, it may not be possible to use it for another workflow ( such as NWChem ).

**Pull request merged**
