### PR TITLE
Existing instances

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
Because the type is ec2 we're getting an error from pyfr.py

```
[15:16:06.679] INFO: Upload complete.
[15:16:06.679] INFO: Updating backend configuration.
[15:16:06.679] ERROR: Exception raise by task.
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 300, in setup_input
    # If we have GPUs use cuda
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by TristanWright** [comment]
[This line](https://github.com/Kitware/HPCCloud/blob/master/server/taskflows/hpccloud/taskflow/pyfr.py#L300)

A check like 
```py
        if machine_spec is not None and int(machine_spec['gpu']) == 1: #301
```
and it runs fine but errors later on. Probably not the best guard because it won't work with clusters that actually have GPU's. Is `machine_spec` or `backend` stored somewhere for running instances?

**Comment by TristanWright** [comment]
Errors on the pyfr_run job
```
[15:16:15.213] ERROR: Unable to retrieve number of slots
  File "cumulus/tasks/job.py", line 266, in submit_job
    .number_of_slots(parallel_env)
  File "cumulus/queue/sge.py", line 101, in number_of_slots
    raise Exception('Unable to retrieve number of slots')
Exception: Unable to retrieve number of slots
```

**Comment by cjh1** [comment]
I will take a look at this, I think we will need to stop the machine_spec in the cluster ...

**Comment by cjh1** [comment]
@TristanWright I have pushed a fix that stores the number of GPUs in the cluster configuration. This allows the PyFR workflow to be using multiple times on the same cluster. This last error you are seeing it unrelated ( I pushed some fixes to HPCCloud-deploy so you will need to re provision ).

**Pull request merged**
