### PR TITLE
simput panel fixes

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
@cjh1 PTAL

**Comment by cjh1** [comment]
@TristanWright this seems to fix #326, but I am not seeing when I try to run a simulation:

configparser.NoSectionError: No section: 'solver-elements-tri'

**Comment by TristanWright** [comment]
I was able to get a run complete. I've never seen that error, I don't think `[solver-elements-tri]` is needed for the 2d-euler-votex? I usually check my input file through the girder ui, is yours the [same as theirs](https://github.com/vincentlab/PyFR/blob/develop/examples/euler_vortex_2d/euler_vortex_2d.ini) after following the instructions?

**Comment by TristanWright** [comment]
This pull will need a `npm install` btw, new Simput and PVW libs

**Comment by cjh1** [comment]
@TristanWright I was following the instruction for 2d-couette ... I will try again.

**Comment by cjh1** [comment]
@TristanWright I am still having issue, may be you wan walk me through what you are doing?

**Comment by TristanWright** [comment]
We got the regular running, merging.

**Pull request merged**
