### PR TITLE
new Visualizer 

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by TristanWright** [comment]
This requires paraview master branch on the server and that the visualizer uses [this file](https://github.com/Kitware/visualizer/blob/master/server/pvw-visualizer.py) from the visualizer repo. 

There are a few issues we ran into testing, but will be ready very soon

**Comment by TristanWright** [comment]
When this is in I can ready the WF icon branch for merging

**Comment by cjh1** [comment]
@TristanWright I have tested this for the PyFR workflow and ParaView workflow. Seems to work fine for me. What is you  assessment of the risk of including this in the release?

**Comment by TristanWright** [comment]
I don't think it's big. As I mentioned above it needs master Paraview and the visualizer file from kitware/visualizer.

**Comment by TristanWright** [comment]
Although as observed it works fine without those, they add some smarter network management. Before frame rate was locked at 30 fps, so even if the user is sending some other actions the server is going to empty the buffer before taking the new actions.

**Comment by cjh1** [comment]
It needs ParaView master? Not sure we want to include a change that needs unreleased code?

**Comment by cjh1** [comment]
Or are you saying that is not a hard requirement?

**Comment by TristanWright** [comment]
Not a hard requirement, Paraview 5.1.2 (latest) will be fine if we want to use a release.

**Comment by cjh1** [comment]
Ok, LGTM

**Pull request merged**
