### PR TITLE
Fix #70 ongoing visualization

### LINKED ISSUE #70: Return to ongoing visualization if already running.
Currently you need to terminate, clone, and rerun task. Add a new icon for this? 

(for vizer and tagger)

### PR DESCRIPTION
**Pull request by TristanWright**
Not ready for merging at time of PR. 

There's an issue where the viewer starts to get a 503 from the web socket after a minute or two so you cannot rejoin or use the ui. In addition, the pvw job seems to have stopped. This stopping can happen when the viewer is active, or when it appears to still be running in the background.

Edit: updated issue description.

### CODE REVIEW

**Comment by cjh1** [comment]
Not sure I understand what you mean by stop in the background, lets discuss in person.

**Comment by cjh1** [comment]
Ok, I am seeing something similar, I see the following in the visualizer log:

2015-10-22 12:34:41-0400 [HTTPChannel,6,192.168.30.149] connection_lost: connection count = 0
2015-10-22 12:34:41-0400 [HTTPChannel,6,192.168.30.149] Starting timer, process will terminate in: 999999sec
2015-10-22 12:34:41-0400 [-] Main loop terminated.

@jourdain Is the bug with termination, looks like it not waiting the required time?

**Comment by jourdain** [comment]
Wondering if 999999 is not properly handled hence the immediate exit?
I didn't saw that when playing with the reconnect.

**Comment by TristanWright** [comment]
(rebased)

**Comment by TristanWright** [comment]
Fixes:
- #98: It takes several minutes for client to connect to running viz task 
- #90: Mesh tagger seems to give up trying to connect after a few minutes 
- #78: Test tagger and visualizer 
- #77: Autobahn even when all viz tasks have ended 
- #70: Return to ongoing visualization if already running. 
- #68: Change spinning gear to something meaningful and informative. 

Can someone confirm?

**Comment by cjh1** [comment]
I am still seeing #98 along with the following error in the console:

Uncaught session not open ( from autobahn ) 

Related to #68 we need to center the spinner on mesh tagger.

Lets merge this but leave those two issues open.

**Comment by cjh1** [comment]
@TristanWright If you can recreate the "Uncaught session not open" can you try a track it down? The unpredictable connection time, will make it hard to demo reliable.

**Comment by cjh1** [comment]
Its sometimes taking literally 3 minutes to connect to the visualizer!

**Comment by TristanWright** [comment]
I'll see if I can find the root of the "Uncaught session not open" I have seen it a couple times when I think about it.

> 3 minutes
😬oh jeez.

**Pull request merged**
