### PR TITLE
Cluster logging

### PR DESCRIPTION
**Pull request by TristanWright**
Tested while a simulation was running with some [Postman](https://www.getpostman.com/) calls. Looks ok here.

@cjh1 PTAL

### CODE REVIEW

**Comment by cjh1** [comment]
@TristanWright Looking good. Is the event stream only connected when the log panel is open?

**Comment by TristanWright** [comment]
Good point, it opens when the whole component is mounted.

On Wed, Apr 27, 2016 at 7:38 AM, Chris Harris <notifications@github.com>
wrote:

> @TristanWright <https://github.com/TristanWright> Looking good. Is the
> event stream only connected when the log panel is open?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/pull/364#issuecomment-215085545>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by TristanWright** [comment]
Because the log can only be opened when there's log contents: if the component loads and there's no log you cannot open the panel to subscribe to the stream.

I'll merge if this looks good otherwise.

**Comment by cjh1** [comment]
I am happy for you to merge this. However, we really don't want to be streaming data from the server that the user may never look at. So we may want the change the behavior of the panel so it can be opened if it has no content in order to trigger the subscription to the stream.

**Comment by TristanWright** [comment]
Only streams when log is open now :)

**Comment by TristanWright** [comment]
cleaned up commit history, going to merge.

**Comment by cjh1** [comment]
Excellent!

**Pull request merged**
