### PR TITLE
fix(ui): closes #348, redux for progress bar

### LINKED ISSUE #348: upload progress bar missing

### PR DESCRIPTION
**Pull request by TristanWright**

### CODE REVIEW

**Comment by cjh1** [comment]
This looks good. I have one concern which is it seems to take a long time ( 5 secs ) before we see the progress bar, during this time its not clear what is going on.

**Comment by TristanWright** [comment]
I haven't seen that, I'm going to test it more with some simulated network
lag.

On Tue, Apr 26, 2016 at 8:35 AM, Chris Harris <notifications@github.com>
wrote:

> This looks good. I have one concern which is it seems to take a long time
> ( 5 secs ) before we see the progress bar, during this time its not clear
> what is going on.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/pull/362#issuecomment-214765826>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
This is running on localhost, so there shouldn't be too much network delay.

**Comment by TristanWright** [comment]
I don't see the 5s lag at all then. For consecutive uploads between
simulations I see a jump back so I'm writing something for that.

On Tue, Apr 26, 2016 at 9:21 AM, Chris Harris <notifications@github.com>
wrote:

> This is running on localhost, so there shouldn't be too much network delay.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/HPCCloud/pull/362#issuecomment-214781083>
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by TristanWright** [comment]
I'm not sure what could be causing the 5s delay. I've refined the behavior a bit this morning. PTAL

**Comment by TristanWright** [comment]
@cjh1, I can't get the 5s lag you showed me. But I think this is ready o/w.

**Comment by cjh1** [comment]
@TristanWright Is the progress bar supposed to go back and forth?

**Comment by TristanWright** [comment]
I'm not sure how you're seeing what you are seeing. :\

**Comment by TristanWright** [comment]
The event sequence should be: 

- **t=0**, progress bar finishes, width 100, opacity 1
- **t=1.5s**, opacity of the bar begins to fade, and a new page is loaded
- **t=2.5**, opacity is 0, and the display of the progress bar is set to 'none'
- the progressBar -hidden- is resetting width: 0, opacity: 1.
- **t=5**, the width of the progressBar is 0, and the opacity: 1, display: block.

Not sure where the fade you're seeing is happening.

**Comment by cjh1** [comment]
I am seeing the progress bar go backwards.

**Comment by patrickoleary** [comment]
well that's unfortunate.

**Comment by TristanWright** [comment]
fixes for multi-file upload in, depends on [pvw 1.3.12](https://github.com/Kitware/paraviewweb/releases) which at time of writing is still travis'ing.

**Comment by cjh1** [comment]
LGTM

**Pull request merged**
