### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by TristanWright**
- Added favicon
- fixed a file upload issue
- fixed spelling (attachement -> attachment)

### CODE REVIEW

**Comment by TristanWright** [comment]
Most immediately noticeable change:
screen shot 2016-08-31 at 10 04 05

**Comment by TristanWright** [comment]
@cjh1 some small changes ready to be taken a look at.

Should we still be merging into release?

**Comment by cjh1** [comment]
@TristanWright I will take a look, if they are low risk target them a release.

**Comment by TristanWright** [comment]
Latest commit addresses #507 table list sorting, the changes in this PR are pretty surface level and don't take a ton of looking into like #497 i.e. no redux actions are involved changes are solely within individual components.

**Comment by cjh1** [comment]
LGTM

**Pull request merged**
